[tool.portray]
port = 8001

[tool.portray.mkdocs.theme]
favicon = "art/hielen2.svg"
logo = "art/hielen2.svg"
name = "material"
palette = {primary = "blue grey", accent = "pink"}

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
TODO = "TODO.md"

[[tool.portray.mkdocs.nav]]
Changelog = "CHANGELOG.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."API Reference"]]
    "Prototypes" = "docs/API Reference/prototypes.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Features" = "docs/API Reference/features.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Parameters" = "docs/API Reference/parameters.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Data" = "docs/API Reference/data.md"

