[tool.portray]
port = 8001
include_reference_documentation = true
#include_reference_documentation = false

[tool.portray.mkdocs.theme]
favicon = "art/hielen.svg"
logo = "art/hielen.svg"
name = "material"
palette = {primary = "blue grey", accent = "pink"}

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
Changelog = "CHANGELOG.md"

[[tool.portray.mkdocs.nav]]
Backlog = "BACKLOG.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."API Reference"]]
    "Prototypes" = "docs/API Reference/prototypes.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "ActionSchemata" = "docs/API Reference/actionschemata.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Features" = "docs/API Reference/features.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Actions" = "docs/API Reference/actions.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Thresholds" = "docs/API Reference/thresholds.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Contexts" = "docs/API Reference/contexts.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "ContextsRoots" = "docs/API Reference/contextsroots.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "Query" = "docs/API Reference/query2.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "Prototypes" = "docs/API Reference/prototypes_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "ActionSchemata" = "docs/API Reference/actionschemata_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "Features" = "docs/API Reference/features_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "Actions" = "docs/API Reference/actions_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "Thresholds" = "docs/API Reference/thresholds_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "Contexts" = "docs/API Reference/contexts_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "ContextsRoots" = "docs/API Reference/contextsroots_v2.md"

    [[tool.portray.mkdocs.nav."API Reference v2"]]
    "Query" = "docs/API Reference/query2_v2.md"

