[tool.portray.mkdocs.theme]
favicon = "art/hielen2.svg"
logo = "art/hielen2.svg"
name = "material"
palette = {primary = "blue grey", accent = "pink"}

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
Changelog = "CHANGELOG.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."API Reference"]]
    "API Prototypes" = "docs/API Reference/prototypes.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "API Elements" = "docs/API Reference/elements.md"

    [[tool.portray.mkdocs.nav."API Reference"]]
    "API Data" = "docs/API Reference/data.md"

